[versions]
kotlin = "1.8.20"
loom = "1.1.+"

minecraft = "1.19.4"
fabric_loader = "0.14.18"

fabric_api = "0.78.0+1.19.4"
fabric_language_kotlin = "1.9.3+kotlin.1.8.20"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
fabric_language_kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric_language_kotlin" }

[plugins]
kotlin_jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin_plugin_serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

loom = { id = "fabric-loom", version.ref = "loom" }




