[versions]
minecraft = "1.20.1"
yarn = "1.20.1+build.2"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn-mappings = { module = "net.fabricmc:yarn", version.ref = "yarn" }
fabric-loader = { module = "net.fabricmc:fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "latest.release" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "latest.release" }
modrinth-minotaur = { id = "com.modrinth.minotaur", version = "latest.release" }
loom = { id = "fabric-loom", version = "latest.release" }