name: release
on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/gradle-build

      - name: Modrinth publish
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: ./gradlew modrinth

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: ./interact/build/libs
